// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYXdvIrRalEReEnB1baUUiUGqo_9EevWs',
    appId: '1:6121737529:web:eed7fccf6a68753eddace8',
    messagingSenderId: '6121737529',
    projectId: 'relay-34040',
    authDomain: 'relay-34040.firebaseapp.com',
    storageBucket: 'relay-34040.appspot.com',
    measurementId: 'G-0QERR798HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRntqF2jqaUd6gay0QnUz8YN_U3AxC1dc',
    appId: '1:6121737529:android:a675361231f60316ddace8',
    messagingSenderId: '6121737529',
    projectId: 'relay-34040',
    storageBucket: 'relay-34040.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT0mwjrTH3EUx9ldCn_Er8lQNd6UR6j5I',
    appId: '1:6121737529:ios:3222bb2df3da5322ddace8',
    messagingSenderId: '6121737529',
    projectId: 'relay-34040',
    storageBucket: 'relay-34040.appspot.com',
    iosClientId: '6121737529-580bjt33aujrb3v8bce55v9tbupa1168.apps.googleusercontent.com',
    iosBundleId: 'com.example.relay',
  );
}
